version: '3.8'
services:
  athena-orgs-api:
    image: athena-orgs-api:latest-prod
    build:
      context: ./orgs_backend
      args:
        CURRENT_ENVIRONMENT: prod
        PORT: 8080
    env_file:
      - ./env/athena-orgs-api.prod.env
  athena-orgs-proxy:
    image: athena-orgs-proxy:latest-prod
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.prod
    env_file:
      - ./env/athena-orgs-web.prod.env
    ports:
      - "80:80"