FROM node:21-alpine as frontend

WORKDIR /app

COPY orgs_web/package.json /app

RUN npm install

COPY orgs_web/ /app

RUN npm run build

FROM nginx:1.25.4-alpine

COPY --from=frontend /app/build /var/www/app.athenalabo.com/html

COPY nginx/nginx.conf.prod /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
